tenant:
  default-tenant-id: 1000

spring:
  redis:
    host: 127.0.0.1
    port: 6379

  datasource:
    dynamic:
      primary: system #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        system:
          url: jdbc:mysql://127.0.0.1:3306/system
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        order:
          url: jdbc:mysql://127.0.0.1:3306/order
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver